### PR TITLE
Add Django 3.0 support

### PR DESCRIPTION
**Pull request by OskarPersson**
Here I have added support for the upcoming Django 3.0. While testing I added a tox configuration which is also reused on travis. I've done my best to keep the support back to Django 1.8 and Python 2.7 but I think it might be worth to consider dropping support for Django 1.8, 1.9, 1.10 and 2.0, as well as Python 2.7 since the Django versions have already lost support and Python 2.7 will do the same January 1st 2020

### CODE REVIEW

**Comment by OskarPersson** [comment]
Travis is testing but I'm not sure why it isn't being reported here? https://travis-ci.org/vittoriozamboni/django-groups-manager/builds/618503585?utm_medium=notification&utm_source=github_status

**Comment by vittoriozamboni** [comment]
Hi Oskar, thank you for your contribution!

Can you please create a branch for the changes (something like django-3-support) and not commit into master directly? 
In this way we can test before merging and stash all the changes.

**Comment by vittoriozamboni** [comment]
My bad, it was already a branch.

**Comment by OskarPersson** [comment]
And now travis is reporting :D

**Pull request merged**
