### PR TITLE
Updgrade to django 3.2...4.2 and Python 3.8...3.11 & minor small improvements

### LINKED ISSUE #63: Migration being created inside groups_manager/migrations
Hi,  first of all, thank you, this library is amazing.

I've noticed in my migrations that I have dependencies on a `0007_alter_group_group_entities_alter_group_group_members_and_more.py`

This is being created, but it's difficult to version in git. Is this missing from your repo? Or am I doing something wrong? 

```
Migrations for 'groups_manager':
  venv/lib/python3.8/site-packages/groups_manager/migrations/0007_alter_group_group_entities_alter_group_group_members_and_more.py
    - Alter field group_entities on group
    - Alter field group_members on group
    - Alter field group_type on group
    - Alter field id on group
    - Alter field parent on group
    - Alter field id on groupentity
    - Alter field id on groupmember
    - Alter field id on groupmemberrole
    - Alter field id on grouptype
    - Alter field django_user on member
    - Alter field id on member
```

thank you!

### PR DESCRIPTION
**Pull request by dalito**
This PR is quite big. Let me know if you want me to split it up. However, the changes are not very complex.

- Upgrade for django 3.2 to 4.2 and Python 3.8 to 3.11
- Use of django´s [JSONField](https://docs.djangoproject.com/en/dev/ref/models/fields/#jsonfield) (added in Django 3.1) instead of the one from [jsonfield](https://pypi.org/project/jsonfield/) package
- Minor documentation updates/fixes
- Enable admin in demo project
- Update testing with tox
- Add a migration missing in release 1.2.0 (#63)

Closes #63

### CODE REVIEW

**Comment by vittoriozamboni** [comment]
Hi David, thank you for the PR. It looks great! 

I am going to test this tomorrow and see if it has breaking changes. Just by looking, all seems good.

**Comment by dalito** [comment]
FYI: I noticed that there is some code marked for deprecation but I left it as it is. I only changed that the deprecated code is no longer used in the package itself.

**Comment by vittoriozamboni** [comment]
We can remove the code in a different PR.

**Comment by vittoriozamboni** [comment]
Excellent work @dalito , really appreciated your contribution!

**Comment by dalito** [comment]
@vittoriozamboni - Thanks a lot for merging the PR so fast and for making the new release!

**Pull request merged**
